### ISSUE TITLE
Must be removed from GitHub

### ISSUE THREAD

**Issue by mirabilos** [grml/grml-live-grml#9]
As this repository contains content under GPL, it must be removed from GitHub as per: http://www.mirbsd.org/permalinks/wlog-10_e20170301-tg.htm

**Comment by evgeni** [comment]
No.
https://www.fsf.org/blogs/licensing/do-githubs-updated-terms-of-service-conflict-with-copyleft

**Comment by mirabilos** [comment]
With the ToS of “Effective date: October 11, 2017”, this is now acceptable.
